### PR TITLE
switch .iteritems to .items to make py3 friendly

### PR DESCRIPTION
**Pull request by Kully**
fixes Issue https://github.com/plotly/publisher/issues/3

ready for review

### CODE REVIEW

**Comment by michaelbabyn** [comment]
This looks good to me @Kully :dancer: I happy this has been addressed!

**Comment by michaelbabyn** [comment]
Although, it would probably be good to update the version number too.

**Comment by Kully** [comment]
> Although, it would probably be good to update the version number too.

to 1.12? https://github.com/plotly/publisher/blob/master/setup.py#L6

**Comment by michaelbabyn** [comment]
0.12 should be good. I just want to make sure that pip uninstalls any old version on my machine.

**Pull request merged**
